In [50]:
# Importing the necessary Modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split # to split data into training and testing sets
from sklearn.model_selection import cross_val_score # for cross validation
from sklearn.metrics import confusion_matrix # to create a confusion matrix

In [51]:
import os
os.getcwd()

'C:\\Users\\aditi\\Downloads\\Python Codes\\exam'

In [52]:
df = pd.read_csv('Sports Data_547601343_1788497867256.csv') #Put exact dataset
df.head()

,Game_number,Result,Avg_team_Age,Match_light_type,Match_format,Bowlers_in_team,Wicket_keeper_in_team,All_rounder_in_team,First_selection,Opponent,...,Max_run_scored_1over,Max_wicket_taken_1over,Extra_bowls_bowled,Min_run_given_1over,Min_run_scored_1over,Max_run_given_1over,extra_bowls_opponent,player_highest_run,Players_scored_zero,player_highest_wicket
0,Game_1,1,18,Day,ODI,3,1,3,Bowling,Srilanka,...,13,3,0,2,3,6,0,54,3,1
1,Game_2,0,24,Day,T20,3,1,4,Batting,Zimbabwe,...,12,1,0,0,3,6,0,69,2,1
2,Game_3,1,24,Day and Night,T20,3,1,2,Bowling,Zimbabwe,...,14,4,0,0,3,6,0,69,3,1
3,Game_4,0,24,Day,ODI,2,1,2,Bowling,Kenya,...,15,4,0,2,3,6,0,73,3,1
4,Game_5,1,24,Night,ODI,1,1,3,Bowling,Srilanka,...,12,4,0,0,3,6,0,80,3,1

In [53]:
df.isnull().sum()

Game_number               0
Result                    0
Avg_team_Age              0
Match_light_type          0
Match_format              0
Bowlers_in_team           0
Wicket_keeper_in_team     0
All_rounder_in_team       0
First_selection           0
Opponent                  0
Season                    0
Audience_number           0
Offshore                  0
Max_run_scored_1over      0
Max_wicket_taken_1over    0
Extra_bowls_bowled        0
Min_run_given_1over       0
Min_run_scored_1over      0
Max_run_given_1over       0
extra_bowls_opponent      0
player_highest_run        0
Players_scored_zero       0
player_highest_wicket     0
dtype: int64

In [54]:
print('The number of rows (observations) is:',df.shape[0],'\n''The number of columns(variables) is:',df.shape[1])

The number of rows (observations) is: 2930
The number of columns(variables) is: 23

In [55]:
df=df.drop(['Game_number','Season','Audience_number','Offshore','First_selection'], axis=1) #drop categorical and range based columns
df.head()

,Result,Avg_team_Age,Match_light_type,Match_format,Bowlers_in_team,Wicket_keeper_in_team,All_rounder_in_team,Opponent,Max_run_scored_1over,Max_wicket_taken_1over,Extra_bowls_bowled,Min_run_given_1over,Min_run_scored_1over,Max_run_given_1over,extra_bowls_opponent,player_highest_run,Players_scored_zero,player_highest_wicket
0,1,18,Day,ODI,3,1,3,Srilanka,13,3,0,2,3,6,0,54,3,1
1,0,24,Day,T20,3,1,4,Zimbabwe,12,1,0,0,3,6,0,69,2,1
2,1,24,Day and Night,T20,3,1,2,Zimbabwe,14,4,0,0,3,6,0,69,3,1
3,0,24,Day,ODI,2,1,2,Kenya,15,4,0,2,3,6,0,73,3,1
4,1,24,Night,ODI,1,1,3,Srilanka,12,4,0,0,3,6,0,80,3,1

In [56]:
df.dtypes

Result                    int64
Avg_team_Age              int64
Match_light_type            str
Match_format                str
Bowlers_in_team           int64
Wicket_keeper_in_team     int64
All_rounder_in_team       int64
Opponent                    str
Max_run_scored_1over      int64
Max_wicket_taken_1over    int64
Extra_bowls_bowled        int64
Min_run_given_1over       int64
Min_run_scored_1over      int64
Max_run_given_1over       int64
extra_bowls_opponent      int64
player_highest_run        int64
Players_scored_zero       int64
player_highest_wicket     int64
dtype: object

In [57]:
X = df.drop("Result", axis=1)

Y = df.pop("Result")

In [58]:
X = pd.get_dummies( X, drop_first = False )

In [59]:
list(X.columns)

['Avg_team_Age',
 'Bowlers_in_team',
 'Wicket_keeper_in_team',
 'All_rounder_in_team',
 'Max_run_scored_1over',
 'Max_wicket_taken_1over',
 'Extra_bowls_bowled',
 'Min_run_given_1over',
 'Min_run_scored_1over',
 'Max_run_given_1over',
 'extra_bowls_opponent',
 'player_highest_run',
 'Players_scored_zero',
 'player_highest_wicket',
 'Match_light_type_Day',
 'Match_light_type_Day and Night',
 'Match_light_type_Night',
 'Match_format_20-20',
 'Match_format_ODI',
 'Match_format_T20',
 'Match_format_Test',
 'Opponent_Australia',
 'Opponent_Bangladesh',
 'Opponent_England',
 'Opponent_Kenya',
 'Opponent_Pakistan',
 'Opponent_South Africa',
 'Opponent_Srilanka',
 'Opponent_West Indies',
 'Opponent_Zimbabwe']

In [60]:
X.dtypes

Avg_team_Age                      int64
Bowlers_in_team                   int64
Wicket_keeper_in_team             int64
All_rounder_in_team               int64
Max_run_scored_1over              int64
Max_wicket_taken_1over            int64
Extra_bowls_bowled                int64
Min_run_given_1over               int64
Min_run_scored_1over              int64
Max_run_given_1over               int64
extra_bowls_opponent              int64
player_highest_run                int64
Players_scored_zero               int64
player_highest_wicket             int64
Match_light_type_Day               bool
Match_light_type_Day and Night     bool
Match_light_type_Night             bool
Match_format_20-20                 bool
Match_format_ODI                   bool
Match_format_T20                   bool
Match_format_Test                  bool
Opponent_Australia                 bool
Opponent_Bangladesh                bool
Opponent_England                   bool
Opponent_Kenya                     bool
Opponent_Pakistan                  bool
Opponent_South Africa              bool
Opponent_Srilanka                  bool
Opponent_West Indies               bool
Opponent_Zimbabwe                  bool
dtype: object

In [61]:
X.head()

,Avg_team_Age,Bowlers_in_team,Wicket_keeper_in_team,All_rounder_in_team,Max_run_scored_1over,Max_wicket_taken_1over,Extra_bowls_bowled,Min_run_given_1over,Min_run_scored_1over,Max_run_given_1over,...,Match_format_Test,Opponent_Australia,Opponent_Bangladesh,Opponent_England,Opponent_Kenya,Opponent_Pakistan,Opponent_South Africa,Opponent_Srilanka,Opponent_West Indies,Opponent_Zimbabwe
0,18,3,1,3,13,3,0,2,3,6,...,False,False,False,False,False,False,False,True,False,False
1,24,3,1,4,12,1,0,0,3,6,...,False,False,False,False,False,False,False,False,False,True
2,24,3,1,2,14,4,0,0,3,6,...,False,False,False,False,False,False,False,False,False,True
3,24,2,1,2,15,4,0,2,3,6,...,False,False,False,False,True,False,False,False,False,False
4,24,1,1,3,12,4,0,0,3,6,...,False,False,False,False,False,False,False,True,False,False

In [62]:
data = df.copy()
data.head()

,Avg_team_Age,Match_light_type,Match_format,Bowlers_in_team,Wicket_keeper_in_team,All_rounder_in_team,Opponent,Max_run_scored_1over,Max_wicket_taken_1over,Extra_bowls_bowled,Min_run_given_1over,Min_run_scored_1over,Max_run_given_1over,extra_bowls_opponent,player_highest_run,Players_scored_zero,player_highest_wicket
0,18,Day,ODI,3,1,3,Srilanka,13,3,0,2,3,6,0,54,3,1
1,24,Day,T20,3,1,4,Zimbabwe,12,1,0,0,3,6,0,69,2,1
2,24,Day and Night,T20,3,1,2,Zimbabwe,14,4,0,0,3,6,0,69,3,1
3,24,Day,ODI,2,1,2,Kenya,15,4,0,2,3,6,0,73,3,1
4,24,Night,ODI,1,1,3,Srilanka,12,4,0,0,3,6,0,80,3,1

In [63]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.30, random_state=1)

In [64]:
from sklearn import tree

In [65]:
dt_model = tree.DecisionTreeClassifier(criterion = 'gini',random_state=1,min_samples_split=2,
    min_samples_leaf=1)

In [66]:
dt_model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=1)

In [67]:
pd.Series(dt_model.feature_importances_,index=X_train.columns).sort_values(ascending=False)

Extra_bowls_bowled                0.127917
player_highest_run                0.125789
Max_run_scored_1over              0.101353
Avg_team_Age                      0.074399
extra_bowls_opponent              0.073833
Max_wicket_taken_1over            0.067990
Min_run_scored_1over              0.065653
Min_run_given_1over               0.053844
Players_scored_zero               0.049881
All_rounder_in_team               0.048477
Bowlers_in_team                   0.036598
player_highest_wicket             0.030289
Max_run_given_1over               0.025276
Opponent_Srilanka                 0.017189
Match_light_type_Day and Night    0.016679
Opponent_England                  0.014444
Opponent_Kenya                    0.014215
Opponent_Australia                0.011816
Opponent_South Africa             0.011595
Opponent_Zimbabwe                 0.010146
Match_light_type_Day              0.008044
Opponent_Pakistan                 0.005605
Opponent_Bangladesh               0.005172
Match_format_T20                  0.003103
Match_format_ODI                  0.000693
Wicket_keeper_in_team             0.000000
Match_format_Test                 0.000000
Match_format_20-20                0.000000
Match_light_type_Night            0.000000
Opponent_West Indies              0.000000
dtype: float64

In [68]:
dt_model.score(X_train,Y_train)

1.0

In [69]:
dt_model.score(X_test,Y_test)

0.9158134243458476

In [70]:
Y_train_predict_class_raw = dt_model.predict(X_train)
Y_test_predict_class_raw = dt_model.predict(X_test)

In [71]:
#Here, we are predicting the probabilities and we can manually input a cutoff value which is different than 0.5.

Y_train_predict_prob_raw = dt_model.predict_proba(X_train)
Y_test_predict_prob_raw = dt_model.predict_proba(X_test)

In [72]:
from sklearn import metrics

In [73]:
print(metrics.confusion_matrix(Y_train,Y_train_predict_class_raw))

[[1722    0]
 [   0  329]]

In [74]:
tn_raw, fp_raw, fn_raw, tp_raw = metrics.confusion_matrix(Y_train,Y_train_predict_class_raw).ravel()
print('True Negative:',tn_raw,'\n''False Positives:' ,fp_raw,'\n''False Negatives:', fn_raw,'\n''True Positives:', tp_raw)

True Negative: 1722
False Positives: 0
False Negatives: 0
True Positives: 329

In [75]:
print(metrics.classification_report(Y_train,Y_train_predict_class_raw))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1722
           1       1.00      1.00      1.00       329

    accuracy                           1.00      2051
   macro avg       1.00      1.00      1.00      2051
weighted avg       1.00      1.00      1.00      2051

In [94]:
reg_dt_model = tree.DecisionTreeClassifier(criterion = 'gini', #Pruning Starts here - Iteration 1
                                       max_depth=3,#upto this depth is where the tree has grown uniformly
                                      min_samples_leaf=10, #ensures that every terminal node (leaf node) have at least 10
                                      #observations in it
                                      min_samples_split=10)

In [95]:
dt_model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=1)

In [96]:

Y_train_predict_class = dt_model.predict(X_train)
Y_test_predict_class = dt_model.predict(X_test)

In [97]:


Y_train_predict_prob = dt_model.predict_proba(X_train)
Y_test_predict_prob = dt_model.predict_proba(X_test)

In [98]:
print(metrics.confusion_matrix(Y_train,Y_train_predict_class))

[[1722    0]
 [   0  329]]

In [99]:
    tn, fp, fn, tp = metrics.confusion_matrix(Y_train,Y_train_predict_class).ravel()
    print('True Negative:',tn,'\n''False Positives:' ,fp,'\n''False Negatives:', fn,'\n''True Positives:', tp)

True Negative: 1722
False Positives: 0
False Negatives: 0
True Positives: 329

In [100]:
print(metrics.classification_report(Y_train,Y_train_predict_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1722
           1       1.00      1.00      1.00       329

    accuracy                           1.00      2051
   macro avg       1.00      1.00      1.00      2051
weighted avg       1.00      1.00      1.00      2051

In [101]:
print(metrics.confusion_matrix(Y_test,Y_test_predict_class),'\n')
tn, fp, fn, tp = metrics.confusion_matrix(Y_test,Y_test_predict_class).ravel()
print('True Negative:',tn,'\n''False Positives:' ,fp,'\n''False Negatives:', fn,'\n''True Positives:', tp)

[[687  48]
 [ 26 118]]

True Negative: 687
False Positives: 48
False Negatives: 26
True Positives: 118

In [102]:
print(metrics.classification_report(Y_test,Y_test_predict_class))

              precision    recall  f1-score   support

           0       0.96      0.93      0.95       735
           1       0.71      0.82      0.76       144

    accuracy                           0.92       879
   macro avg       0.84      0.88      0.86       879
weighted avg       0.92      0.92      0.92       879

In [103]:
reg_dt_model = tree.DecisionTreeClassifier(criterion = 'gini', #Pruning Starts here - Iteration 2
                                       max_depth=13,#upto this depth is where the tree has grown uniformly
                                      min_samples_leaf=30, #ensures that every terminal node (leaf node) have at least 10
                                      #observations in it
                                      min_samples_split=10)

In [104]:
reg_dt_model.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=13, min_samples_leaf=30, min_samples_split=10)

In [105]:

Y_train_predict_class = reg_dt_model.predict(X_train)
Y_test_predict_class = reg_dt_model.predict(X_test)

In [106]:


Y_train_predict_prob = reg_dt_model.predict_proba(X_train)
Y_test_predict_prob = reg_dt_model.predict_proba(X_test)

In [107]:
print(metrics.confusion_matrix(Y_train,Y_train_predict_class))

[[1712   10]
 [ 295   34]]

In [108]:
    tn, fp, fn, tp = metrics.confusion_matrix(Y_train,Y_train_predict_class).ravel()
    print('True Negative:',tn,'\n''False Positives:' ,fp,'\n''False Negatives:', fn,'\n''True Positives:', tp)

True Negative: 1712
False Positives: 10
False Negatives: 295
True Positives: 34

In [109]:
print(metrics.classification_report(Y_train,Y_train_predict_class))

              precision    recall  f1-score   support

           0       0.85      0.99      0.92      1722
           1       0.77      0.10      0.18       329

    accuracy                           0.85      2051
   macro avg       0.81      0.55      0.55      2051
weighted avg       0.84      0.85      0.80      2051

In [110]:
print(metrics.confusion_matrix(Y_test,Y_test_predict_class),'\n')
tn, fp, fn, tp = metrics.confusion_matrix(Y_test,Y_test_predict_class).ravel()
print('True Negative:',tn,'\n''False Positives:' ,fp,'\n''False Negatives:', fn,'\n''True Positives:', tp)

[[731   4]
 [134  10]]

True Negative: 731
False Positives: 4
False Negatives: 134
True Positives: 10

In [111]:
print(metrics.classification_report(Y_test,Y_test_predict_class))

              precision    recall  f1-score   support

           0       0.85      0.99      0.91       735
           1       0.71      0.07      0.13       144

    accuracy                           0.84       879
   macro avg       0.78      0.53      0.52       879
weighted avg       0.82      0.84      0.78       879

In [45]:
#END